### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by TimWhiting** [gaetschwartz/build-runner#6]
Trying on a new computer, js-yaml fails to be found. Is there something special you have to do for extensions to add dependencies?
```
[2021-10-22 14:12:51.874] [exthost] [error] Activating extension gaetschwartz.build-runner failed due to an error:
[2021-10-22 14:12:51.874] [exthost] [error] Error: Cannot find module 'js-yaml'
Require stack:
- /home/tim/.vscode/extensions/gaetschwartz.build-runner-0.5.1/out/extension.js
- /snap/code/78/usr/share/code/resources/app/out/vs/loader.js
- /snap/code/78/usr/share/code/resources/app/out/bootstrap-amd.js
- /snap/code/78/usr/share/code/resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.i._load (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28495)
    at Function.b._load (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:25083)
    at Function.d._load (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:60224)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at v (/snap/code/78/usr/share/code/resources/app/out/vs/loader.js:4:698)
    at Object.<anonymous> (/home/tim/.vscode/extensions/gaetschwartz.build-runner-0.5.1/out/extension.js:17:14)
    at Module.s._compile (/snap/code/78/usr/share/code/resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.i._load (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28495)
    at Function.b._load (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:25083)
    at Function.d._load (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:60224)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.r [as __$__nodeRequire] (/snap/code/78/usr/share/code/resources/app/out/vs/loader.js:5:101)
    at w._loadCommonJSModule (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:26492)
    at w._doActivateExtension (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12722)
    at w._activateExtension (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:11695)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 8)
    at async Promise.all (index 0)[2021-10-22 14:12:51.874] [exthost] [error] Activating extension gaetschwartz.build-runner failed due to an error:
[2021-10-22 14:12:51.874] [exthost] [error] Error: Cannot find module 'js-yaml'
Require stack:
- /home/tim/.vscode/extensions/gaetschwartz.build-runner-0.5.1/out/extension.js
- /snap/code/78/usr/share/code/resources/app/out/vs/loader.js
- /snap/code/78/usr/share/code/resources/app/out/bootstrap-amd.js
- /snap/code/78/usr/share/code/resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.i._load (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28495)
    at Function.b._load (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:25083)
    at Function.d._load (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:60224)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at v (/snap/code/78/usr/share/code/resources/app/out/vs/loader.js:4:698)
    at Object.<anonymous> (/home/tim/.vscode/extensions/gaetschwartz.build-runner-0.5.1/out/extension.js:17:14)
    at Module.s._compile (/snap/code/78/usr/share/code/resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.i._load (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28495)
    at Function.b._load (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:25083)
    at Function.d._load (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:60224)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.r [as __$__nodeRequire] (/snap/code/78/usr/share/code/resources/app/out/vs/loader.js:5:101)
    at w._loadCommonJSModule (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:26492)
    at w._doActivateExtension (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12722)
    at w._activateExtension (/snap/code/78/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:11695)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 8)
    at async Promise.all (index 0)
```

**Comment by gaetschwartz** [comment]
Hi, realized that as well, fixed it.
